# Generated by Django 6.0.3 on 2026-04-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0017_auto_20210513_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid_table',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deliv_form',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
