# Generated by Django 6.0.3 on 2026-04-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0018_alter_bid_table_id_alter_deliv_form_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliv_form',
            name='auct_time',
            field=models.DateTimeField(),
        ),
    ]
