# Generated by Django 6.0.3 on 2026-04-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0019_alter_deliv_form_auct_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliv_form',
            name='auct_time',
            field=models.TimeField(),
        ),
    ]
